version:                    '3.1'

services:

  ### mail ###################################################
  mailhog:
    image: mailhog/mailhog:latest
    container_name: bs-mailhog
    ports:
      - "8026:8025"
      - "1025:1025"


  ### db ###################################################
  db:
    image:                  mysql:8
    container_name:         bs-db
    #command:                --default-authentication-plugin=mysql_native_password
    restart:                always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    #      - TZ=${WORKSPACE_TIMEZONE}
    ports:
      - "${MYSQL_PORT}:3306"

  ## phpMyAdmin ###########################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name:         bs-pma
    environment:
      #      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - MYSQL_USER=${PMA_USER}
      - MYSQL_PASSWORD=${PMA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${PMA_ROOT_PASSWORD}
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - db

  ## php ###########################################
  php-fpm:
    build: docker/php-fpm
    container_name: bs-php-fpm
    working_dir: /app
    volumes:
      - ./src/app:/app:rw,cached
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

  ## web ###########################################
  web:
    image:                  nginx:latest
    container_name:         bs-web
    ports:
      - "80:80"
      - "443:443"
    working_dir: /
    hostname: bs.local
    volumes:
      - ./src/app:/app
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
    links:
      - php-fpm
    networks:
      default:
        aliases:
          - bs.local
